<div class="bg-green-300"></div>
<div class="bg-green-400"></div>
<div class="bg-yellow-400"></div>
<div class="bg-red-400"></div>
<div class="bg-red-400"></div>
<div class="bg-green-100 text-green-800"></div>
<div class="bg-green-400 text-green-900"></div>
<div class="bg-yellow-400 text-yellow-900"></div>
<div class="bg-red-600 text-white"></div>
<div class="bg-red-600 text-white"></div>
<div class="bg-red-600 text-white"></div>
<div class="bg-red-600 text-white"></div>
<div class="bg-gray-100 text-gray-500"></div>